services:

  web:
    build: ./web
    container_name: clim_web
    restart: always
    expose:
      - "80"
    volumes:
      - ./web/src:/var/www/html
      - ./ca/data/root_ca.crt:/var/www/storage/certificates/root_ca.crt:ro 
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
      migrations:
        condition: service_completed_successfully 
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_BASE_URL: http://clim_api:5001
      APP_VERSION: ${APP_VERSION}
    networks:
    - clim_network

  api:
    build: ./api
    container_name: clim_api
    environment:
      PYTHONPATH: /app/shared
      HUB_URL: ${HUB_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ./shared:/app/shared
    restart: always

    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started
    networks:
    - clim_network

  db:
    image: mariadb:11
    restart: always
    container_name: clim_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL","mariadb-admin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
    - clim_network


  scheduler:
    build: ./scheduler
    container_name: clim_scheduler
    environment:
      PYTHONPATH: /app/shared
      HUB_WRITE_URL: ${HUB_WRITE_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SCHEDULER_INTERVAL: ${SCHEDULER_INTERVAL}
      DISCOVERY_INTERVAL: ${DISCOVERY_INTERVAL}

    volumes:
      - ./shared:/app/shared
    restart: always
    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    networks:
    - clim_network

  modbus-hub:
    build: ./modbus-hub
    container_name: modbus_hub
    #ports:
    #  - "${MODBUS_PORT}:8500"
    restart: always
    networks:
    - clim_network

  migrations:
    image: mariadb:11
    container_name: clim_migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/migrations:/migrations
      - ./mysql/migrate.sh:/migrate.sh
    entrypoint:
      - bash
      - /migrate.sh
    restart: "no"   
    networks:
    - clim_network

  proxy:
      image: jc21/nginx-proxy-manager:latest
      container_name: clim_proxy
      restart: always

      ports:
        - "80:80"
        - "443:443"
        - "81:81"

      volumes:
        - ./proxy/data:/data
        - ./proxy/letsencrypt:/etc/letsencrypt

      networks:
        - clim_network

  ca:
    build: ./ca
    container_name: clim_ca
    restart: "no"

    environment:
      SERVER_IP: ${HOST_IP}
      CA_PASSWORD: ${CA_PASSWORD}

    volumes:
      - ./ca/data:/home/step

    networks:
      clim_network:
        aliases:
          - clim-ca

volumes:
  db_data:

networks:
  clim_network:
    driver: bridge
