services:

  web:
    build: ./web
    container_name: clim_web
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      DB_HOST: db
      DB_NAME: clim_manager
      DB_USER: climuser
      DB_PASSWORD: climpassword
      API_BASE_URL: http://clim_api:5001
      HUB_URL_EXTERNAL: "http://10.0.0.39:8500/read"
      HUB_WRITE_URL_EXTERNAL: "http://10.0.0.39:8500/write"

  api:
    build: ./api
    container_name: clim_api
    environment:
      PYTHONPATH: /app/shared
      HUB_URL: http://modbus-hub:8500/read
      DB_HOST: db
      DB_NAME: clim_manager
      DB_USER: climuser
      DB_PASSWORD: climpassword
    volumes:
      - ./shared:/app/shared
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started

  db:
    image: mariadb:11
    restart: always
    container_name: clim_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clim_manager
      MYSQL_USER: climuser
      MYSQL_PASSWORD: climpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 20

  scheduler:
    build: ./scheduler
    container_name: clim_scheduler
    environment:
      PYTHONPATH: /app/shared
      HUB_WRITE_URL: http://modbus-hub:8500/write
      DB_HOST: db
      DB_NAME: clim_manager
      DB_USER: climuser
      DB_PASSWORD: climpassword
    volumes:
      - ./shared:/app/shared
    restart: always
    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started

  modbus-hub:
    build: ./modbus-hub
    container_name: modbus_hub
#    environment:
#      MODBUS_PROXY_IP: 10.5.0.20
#      MODBUS_PROXY_PORT: 502
#      MODBUS_PROXY_SLAVE: 1
#      MODBUS_PROXY_LISTEN_PORT: 1502
#      MODBUS_PROXY_STORE_SIZE: 10000
    ports:
      - "8500:8500"
#     - "1502:1502"
    restart: always

volumes:
  db_data:
