services:

  web:
    build: ./web
    container_name: clim_web
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_BASE_URL: http://clim_api:5001
      APP_VERSION: ${APP_VERSION}

  api:
    build: ./api
    container_name: clim_api
    environment:
      PYTHONPATH: /app/shared
      HUB_URL: ${HUB_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ./shared:/app/shared
    restart: always

    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started

  db:
    image: mariadb:11
    restart: always
    container_name: clim_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL","mariadb-admin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  scheduler:
    build: ./scheduler
    container_name: clim_scheduler
    environment:
      PYTHONPATH: /app/shared
      HUB_WRITE_URL: ${HUB_WRITE_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SCHEDULER_INTERVAL: ${SCHEDULER_INTERVAL}
      DISCOVERY_INTERVAL: ${DISCOVERY_INTERVAL}

    volumes:
      - ./shared:/app/shared
    restart: always
    depends_on:
      db:
        condition: service_healthy
      modbus-hub:
        condition: service_started

  modbus-hub:
    build: ./modbus-hub
    container_name: modbus_hub
    #ports:
    #  - "${MODBUS_PORT}:8500"
    restart: always

volumes:
  db_data:
